### ISSUE TITLE
Add LED Support on HK1 Box (S905x3) 

### ISSUE THREAD

**Issue by Ausaci** [unifreq/linux-5.15.y#18]
Hi, could you add LED module support on HK1 Box (S905x3). I have seen a modified dtb on the post ([https://www.znds.com/tv-1200939-1-1.html](https://www.znds.com/tv-1200939-1-1.html)) by adding following codes.

```
leds {
    compatible = "gpio-leds";
    status = "okay";
    sys_led {
        label = "sys_led";
        gpios = <0x75 0x0b 0x00>; //0x75是bank@14的phandle，注意修改自己的
        default-state = "on";
        linux,default-trigger = "default-on";
    };
};

zvfd {
    compatible = "z,vfd";
    dev_name = "zvfd";
    status = "okay";
};
```

It works. 

I know the LED display can be controlled by `armbian-led` or `openwrt-led` provided by [ophub/amlogic-s9xxx-armbian](https://github.com/ophub/amlogic-s9xxx-armbian). But it does not work for the Bule LED at the left of the display.

**Comment by huapox** [comment]
Ref https://github.com/ophub/amlogic-s9xxx-armbian/issues/414#issuecomment-1275432615
